version: '3'
services:
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_wordpress
        ports:
            - "8080:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
  db:
        container_name: mysql_wordpress
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - "./mysql_data:/var/lib/mysql"     
  wordpress: 
        container_name: wordpress
        image: wordpress
        depends_on: 
          - db
        ports: 
          - "80:80"  
        restart: always  
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_PASSWORD: wordpress_user_password
            WORDPRESS_DB_USER: wordpress_user
        volumes: 
           - "./wordpress_data:/var/www/html" 
    
   
    